apiVersion: v1
kind: Service
metadata:
  name: fall-detection
  namespace: safeguard
  labels:
    app.kubernetes.io/name: fall-detection
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: fall-detection
  ports:
    - name: http
      port: 8000
      targetPort: 8000
