apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: safeguard
  namespace: safeguard
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    kubernetes.io/ingress.class: traefik
spec:
  ingressClassName: traefik
  rules:
    - host: snapdragon.upayan.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 3000
    - host: api-snapdragon.upayan.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 8080
    - host: fall-snapdragon.upayan.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fall-detection
                port:
                  number: 8000
