apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: safeguard
  namespace: safeguard
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "25m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - snapdragon.upayan.dev
        - api-snapdragon.upayan.dev
        - ppe-snapdragon.upayan.dev
        - fall-snapdragon.upayan.dev
      secretName: safeguard-tls
  rules:
    - host: snapdragon.upayan.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 3000
    - host: api-snapdragon.upayan.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 8080
    - host: ppe-snapdragon.upayan.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ppe-detection
                port:
                  number: 8000
    - host: fall-snapdragon.upayan.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fall-detection
                port:
                  number: 8000
