apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: safeguard-logs
  namespace: safeguard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # k3s: local-path | minikube: standard | cloud: default
  storageClassName: local-path
