apiVersion: v1
kind: Service
metadata:
  name: ppe-detection
  namespace: safeguard
spec:
  selector:
    app: ppe-detection
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30800
